version: '3.7'

services:
 database:
  image: mcr.microsoft.com/mssql/server:2017-latest
  container_name: database
  environment:
   MSSQL_DATABASE: compose
   ACCEPT_EULA: Y
   SA_PASSWORD: pMsql20-
   MSSQL_PID: Standard 
  ports:
   - 1433:1433
  volumes:
   - compose:/var/opt/mssql
  networks:
   - backendNetwork
        
 springapi:
  image: openjdk:8
  container_name: springapi
  ports:
   - 8080:8080
  depends_on:
   - database
  volumes:
   - ./Spring/target/docker-compose.jar:/docker-compose.jar
  command: ["java", "-jar", "docker-compose.jar"]
  networks:
   - backendNetwork
   - frontendNetwork
   
 angular:
  image: nginx:alpine
  container_name: angular
  ports:
   - 4200:80
  depends_on:
   - springapi
  volumes:
   - ./nginx.conf:/etc/nginx/nginx.conf
   - ./Angular/dist/Angular/:/usr/share/nginx/html
   networks:
    - frontendNetwork
volumes:
 compose:
 
networks:
 backendNetwork
 frontendNetwork
            
        
    
    